// src/components/Entry.tsx
export interface EntryProps {
  item: Item;
  deleteFn: (id: string) => void;
}

export interface Item {
  id: string;
  content: string;
  created: Date;
}

export function Entry({ item: entry, deleteFn }: EntryProps) {
  return (
    <div key={entry.id} className="flex flex-1 gap-2">
      <span className="flex flex-1 gap-2">
        <span className="dark:text-gray-200 text-gray-500 font-light">
          {entry.created.toLocaleString()}
        </span>
        <span>{entry.content}</span>
      </span>
      <span>
        <button onClick={() => deleteFn(entry.id)}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="size-6"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M15 12H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
            />
          </svg>
        </button>
      </span>
    </div>
  );
}

// src/lib/components/Entry.svelte
<script lang="ts">
	import type { StructuredEntity } from '$lib/StructuredEntity';
	import { content } from '$lib/state/localstorage';

	export let state: StructuredEntity;

	function onDuplicate() {
		const newEntry: StructuredEntity = { ...state, created: new Date() };
		content.update((state) => {
			const prev = JSON.parse(state);
			return JSON.stringify([newEntry, ...prev]);
		});
	}
</script>

<p class="entry">
	<em>{state.created}</em>: <span class="entry-content">{state.content}</span>
	<button on:click={onDuplicate}>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke-width="1.5"
			stroke="currentColor"
			class="w-6 h-6"
		>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				d="M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75a1.125 1.125 0 01-1.125-1.125V7.875c0-.621.504-1.125 1.125-1.125H6.75a9.06 9.06 0 011.5.124m7.5 10.376h3.375c.621 0 1.125-.504 1.125-1.125V11.25c0-4.46-3.243-8.161-7.5-8.876a9.06 9.06 0 00-1.5-.124H9.375c-.621 0-1.125.504-1.125 1.125v3.5m7.5 10.375H9.375a1.125 1.125 0 01-1.125-1.125v-9.25m12 6.625v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5a1.125 1.125 0 01-1.125-1.125v-1.5a3.375 3.375 0 00-3.375-3.375H9.75"
			/>
		</svg>
	</button>
</p>

<style>
	svg {
		width: 24px;
	}

	button {
		display: inline;
	}
</style>
